orders/urls.py
from django.urls import path

from orders.views import (OrderCreateView, OrderDetailView, OrderListView,
                          OrderUpdateView, add_quantity, add_to_cart,
                          export_orders_to_excel, remove_from_cart,
                          subtract_quantity, view_cart)

app_name = 'orders'

urlpatterns = [
    path('view/', view_cart, name='view-cart'),
    path('add/<int:product_id>/', add_to_cart, name='add-to-cart'),
    path('add_quantity/<int:cart_item_id>/', add_quantity, name='add-quantity'),
    path('subtract_quantity/<int:cart_item_id>/', subtract_quantity, name='subtract-quantity'),
    path('remove/<int:cart_item_id>/', remove_from_cart, name='remove-from-cart'),
    path('create_order/', OrderCreateView.as_view(), name='create-order'),
    path('order_list/', OrderListView.as_view(), name='order-list'),
    path('order_detail/<int:pk>', OrderDetailView.as_view(), name='order-detail'),
    path('order_update/<int:pk>', OrderUpdateView.as_view(), name='order-update'),
    path('export-orders-to-excel/', export_orders_to_excel, name='export-orders-to-excel'),
]

products/urls.py
from django.urls import path

from products.views import ProductListView

app_name = 'products'

urlpatterns = [
    path("", ProductListView.as_view(), name='product-list'),
    path("page/<int:page>/", ProductListView.as_view(), name='paginator'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('auth/', include('users.urls')),
    path('orders/', include('orders.urls')),
    path("", IndexView.as_view(), name="home")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

users/urls.py
from django.urls import path

from users.views import UserLoginView, UserLogoutView, UserRegistrationView

app_name = 'users'

urlpatterns = [
    path("login/", UserLoginView.as_view(), name='login'),
    path("logout/", UserLogoutView.as_view(), name='logout'),
    path('register/', UserRegistrationView.as_view(), name='register'),
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


def upload_to(instance, filename):
    # instance.category - это поле ForeignKey, связывающее продукт с категорией
    category_name = instance.category.name if instance.category else 'uncategorized'
    return f"{category_name}/{filename}"


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField(upload_to=upload_to)
    category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

products/views.py
from django.views.generic import ListView, TemplateView

from products.models import Product, ProductCategory


class IndexView(TemplateView):
    template_name = 'products/home.html'


class ProductListView(ListView):
    model = Product
    template_name = 'products/product-list.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.objects.all()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context

products/templates/base.html
<!-- products/templates/products/base.html -->
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %}My Shop{% endblock %}</title>
</head>
<body>
    <div class="header">
        <div class="container">
            <h1>{% block header %}{% endblock %}</h1>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'products:product-list' %}">Products</a>
                    </li>
                  </ul>

                  <!-- Условия для отображения кнопок в зависимости от авторизации пользователя -->
                  {% if user.is_authenticated %}
                      <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'orders:order-list' %}">Заказы</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'orders:view-cart' %}">Корзина</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                      </ul>
                  {% else %}
                    <ul class="navbar-nav ms-auto">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                      </li>
                    </ul>
                  {% endif %}
                </div>
              </div>
            </nav>
        </div>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>

    <div class="footer mt-5 bg-light text-center">
        <div class="container">
            <p>&copy; 2023 My Shop. All rights reserved.</p>

            <!-- Ссылки на социальные сети с использованием стилей Bootstrap -->
            <div class="social-links mt-3">
                <a href="#" class="text-dark me-3">Facebook</a>
                <a href="#" class="text-dark me-3">Twitter</a>
                <a href="#" class="text-dark me-3">Instagram</a>
            </div>
        </div>
    </div>

    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>