orders/urls.py
from django.urls import path

from orders.views import (OrderCreateView, OrderDetailView, OrderListView,
                          OrderUpdateView, add_quantity, add_to_cart,
                          export_orders_to_excel, remove_from_cart,
                          subtract_quantity, view_cart)

app_name = 'orders'

urlpatterns = [
    path('view/', view_cart, name='view-cart'),
    path('add/<int:product_id>/', add_to_cart, name='add-to-cart'),
    path('add_quantity/<int:cart_item_id>/', add_quantity, name='add-quantity'),
    path('subtract_quantity/<int:cart_item_id>/', subtract_quantity, name='subtract-quantity'),
    path('remove/<int:cart_item_id>/', remove_from_cart, name='remove-from-cart'),
    path('create_order/', OrderCreateView.as_view(), name='create-order'),
    path('order_list/', OrderListView.as_view(), name='order-list'),
    path('order_detail/<int:pk>', OrderDetailView.as_view(), name='order-detail'),
    path('order_update/<int:pk>', OrderUpdateView.as_view(), name='order-update'),
    path('export-orders-to-excel/', export_orders_to_excel, name='export-orders-to-excel'),
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('auth/', include('users.urls')),
    path('orders/', include('orders.urls')),
    path("", IndexView.as_view(), name="home")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

orders/models.py
from django.db import models
from django.db.models import F, Sum

from products.models import Product
from users.models import EmailUser


class Cart(models.Model):
    user = models.OneToOneField(EmailUser, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')

    def __str__(self):
        return f"Cart for {self.user.email}"

    # def total_price(self):
    #     cart_items = self.cartitem_set.all()
    #     total_sum = sum([item.total_price() for item in cart_items])
    #     return total_sum
    #
    # def total_quantity(self):
    #     cart_items = self.cartitem_set.all()
    #     total_sum = sum([item.quantity for item in cart_items])
    #     return total_sum

    def calculate_totals(self):
        totals = (
            self.cartitem_set
            .aggregate(
                total_quantity=Sum('quantity'),
                total_price=Sum(F('quantity') * F('product__price'))
            )
        )
        self.total_quantity = totals['total_quantity'] or 0
        self.total_price = totals['total_price'] or 0
        self.save()

    def to_json(self):
        self.calculate_totals()
        cart = {
            "items": [],
            "total_price": float(self.total_price),
        }
        for item in self.cartitem_set.all():
            cart_item = {
                "product": item.product.name,
                "quantity": item.quantity,
                "total_price": float(item.total_price())
            }
            cart["items"].append(cart_item)
        return cart


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name} in {self.cart.user.email}'s cart"

    def total_price(self):
        total_sum = self.product.price * self.quantity
        return total_sum


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3
    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )
    full_name = models.CharField(max_length=150)
    email = models.EmailField()
    address = models.CharField(max_length=256)
    phone = models.CharField(max_length=30)
    cart_history = models.JSONField(default=dict)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(default=CREATED, choices=STATUSES)
    initiator = models.ForeignKey(EmailUser, on_delete=models.CASCADE)
    comment = models.TextField()

    def __str__(self):
        return f'Order #{self.pk} for {self.full_name}'

orders/forms.py
from django.forms import ModelForm

from orders.models import Order


class OrderForm(ModelForm):

    class Meta:
        model = Order
        fields = ("full_name", "email", "address", "phone", "comment")


class ChangeOrderStatusForm(ModelForm):

    class Meta:
        model = Order
        fields = ("status", )

orders/views.py
import io
from datetime import timezone

from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.utils.encoding import force_str
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from openpyxl.workbook import Workbook

from orders.forms import ChangeOrderStatusForm, OrderForm
from orders.models import Cart, CartItem, Order
from products.models import Product


@login_required
def view_cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart.calculate_totals()  # Предварительно загружаем агрегированные значения
    cart_items = cart.cartitem_set.select_related('product').all()  # Получаем все товары в корзине
    context = {
        'cart': cart,
        'cart_items': cart_items,
        'total_price': cart.total_price,
        'total_quantity': cart.total_quantity
    }

    return render(request, 'orders/view-cart.html', context)


@login_required
def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    cart_item.quantity += 1
    cart_item.save()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


def add_quantity(request, cart_item_id: int):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    cart_item.quantity += 1
    cart_item.save()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


def subtract_quantity(request, cart_item_id: int):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
    cart_item.save()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(id=cart_item_id)
    cart_item.delete()
    return HttpResponseRedirect(request.META["HTTP_REFERER"])


class OrderCreateView(CreateView):
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders:order-list')

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        cart = Cart.objects.get(user=self.request.user)
        form.instance.cart_history = cart.to_json()
        cart.delete()
        return super(OrderCreateView, self).form_valid(form)


class OrderListView(ListView):
    template_name = "orders/order-list.html"
    context_object_name = 'orders'

    def get_queryset(self):
        if self.request.user.is_staff:
            return Order.objects.all().order_by('status', '-created_at')
        return Order.objects.filter(initiator=self.request.user).order_by('status', '-created_at')


class OrderDetailView(DetailView):
    template_name = 'orders/order-detail.html'
    model = Order
    context_object_name = "order"


class OrderUpdateView(UpdateView):
    template_name = 'orders/order-update.html'
    model = Order
    form_class = ChangeOrderStatusForm
    context_object_name = "order"

    def get_success_url(self):
        return reverse_lazy("orders:order-detail", args=[self.object.pk])


@user_passes_test(lambda user: user.is_staff)
def export_orders_to_excel(request):
    # Получите данные о заказах, которые вам нужны для статистики
    orders = Order.objects.all()

    # Создайте новый файл Excel и добавьте в него данные
    workbook = Workbook()

    # Лист для заказов
    worksheet_orders = workbook.active
    worksheet_orders.title = 'Orders'

    # Заголовки для листа заказов
    worksheet_orders.append(['Order ID', 'User', 'Total Price', 'Date Created'])

    # Добавление данных для заказов
    for order in orders:
        date_created_utc = order.created_at.astimezone(timezone.utc).replace(tzinfo=None)
        worksheet_orders.append([order.id, order.initiator.email, order.cart_history["total_price"], date_created_utc])

    worksheet_products = workbook.create_sheet(title='Products')  # Лист для продуктов

    # Заголовки для листа продуктов
    worksheet_products.append(['Product Name', 'Total Quantity Sold', 'Total Sales Amount'])
    products_info = {}  # Словарь для хранения информации о продуктах

    # Обработка заказов для получения информации о продуктах
    for order in orders:
        for item in order.cart_history["items"]:
            product_name = item["product"]
            quantity_sold = item["quantity"]
            total_price = item["total_price"]

            if product_name in products_info:
                # Если продукт уже встречался, обновляем информацию
                products_info[product_name]['quantity_sold'] += quantity_sold
                products_info[product_name]['total_sales'] += total_price
            else:
                # Если продукт встречается впервые, добавляем информацию
                products_info[product_name] = {
                    'quantity_sold': quantity_sold,
                    'total_sales': total_price
                }

    # Добавление информации о продуктах на лист
    for product_name, info in products_info.items():
        worksheet_products.append([product_name, info['quantity_sold'], info['total_sales']])

    # Добавление строки с общими данными внизу таблицы с продуктами
    total_quantity_all_products = sum(info['quantity_sold'] for info in products_info.values())
    total_sales_all_products = sum(info['total_sales'] for info in products_info.values())
    worksheet_products.append(['Total', total_quantity_all_products, total_sales_all_products])

    excel_data = io.BytesIO()  # Создание байтового объекта для временного хранения файла в памяти
    workbook.save(excel_data)  # Сохранение книги в байтовый объект
    excel_data.seek(0)  # Перемотка байтового объекта в начало

    # Создание HTTP-ответа с содержимым файла Excel
    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = force_str('attachment; filename=orders_statistics.xlsx')
    response.write(excel_data.read())

    return response

orders/templates/orders/order-create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <h2>Create Order</h2>
      <form method="post" action="{% url 'orders:create-order' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Place Order">
      </form>
    </div>
  </div>
</div>
{% endblock %}

orders/templates/orders/order-detail.html
<!-- orders/templates/orders/order-detail.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container mt-5">
  {% block status %}
    <p>Status: <span class="badge bg-primary">{{ order.get_status_display }}</span></p>
    {% if user.is_staff %}
      <p><a href="{% url 'orders:order-update' order.id %}" class="badge bg-primary">Изменить</a></p>
    {% endif %}
  {% endblock status %}

  <h4>Order Items</h4>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Total Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in order.cart_history.items %}
        <tr>
          <td>{{ item.product }}</td>
          <td>{{ item.quantity }}</td>
          <td>{{ item.total_price }} ₽</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <h4>Total Price: {{ order.cart_history.total_price }} ₽</h4>

  {% if user.is_staff %}
    <div class="mt-4">
      <h5 class="mb-3">Информация о заказе:</h5>
      <p class="mb-2"><strong>Address:</strong> {{ order.address }}</p>
      <p class="mb-2"><strong>Comment:</strong> {{ order.comment }}</p>
    </div>
  {% endif %}
</div>

{% endblock %}

orders/templates/orders/order-list.html
<!-- orders/templates/orders/order-list.html -->

{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">

  {% if user.is_staff %}
  <h2>Orders</h2>
  <a href="{% url 'orders:export-orders-to-excel' %}" class="btn btn-success mb-3">Download Excel</a>
  {% else %}
  <h2>Your Orders</h2>
  {% endif %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Full Name</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Status</th>
        <th scope="col">Created At</th>
        <th scope="col">Details</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
        <tr>
          <th scope="row">{{ order.id }}</th>
          <td>{{ order.full_name }}</td>
          <td>{{ order.phone }}</td>
          <td>{{ order.get_status_display }}</td>
          <td>{{ order.created_at }}</td>
          <td><a href="{% url 'orders:order-detail' order.id %}" class="btn btn-primary">Details</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

orders/templates/orders/order-update.html
<!-- orders/templates/orders/order-update.html -->
{% extends 'orders/order-detail.html' %}
{% load static %}

{% block status %}
    <form method="post" class="mt-3">
      {% csrf_token %}
      {{ form.as_p }}
        <p>
            <button type="submit" class="badge bg-primary">Сохранить</button>
        </p>

    </form>
{% endblock %}

orders/templates/orders/view-cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <ul class="list-group">
        {% for cart_item in cart_items %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ cart_item.product.name }}
            <span class="badge bg-primary rounded-pill">
              <a href="{% url 'orders:subtract-quantity' cart_item.id %}" class="text-white">-</a>
              {{ cart_item.quantity }}
              <a href="{% url 'orders:add-quantity' cart_item.id %}" class="text-white">+</a>
            </span>
            <span class="badge bg-success rounded-pill">{{ cart_item.total_price }} ₽</span>
            <a href="{% url 'orders:remove-from-cart' cart_item.id %}" class="btn btn-danger">Remove</a>
          </li>
        {% endfor %}
      </ul>

      <div class="mt-3">
        <p>Total Quantity: <span class="badge bg-primary">{{ total_quantity }}</span></p>
        <p>Total Price: <span class="badge bg-success">{{ total_price }} ₽</span></p>
      </div>

      <a href="{% url 'orders:create-order' %}" class="btn btn-primary mt-3">Place Order</a>
    </div>
  </div>
</div>
{% endblock %}