orders/urls.py
from django.urls import path

from orders.views import (OrderCreateView, OrderDetailView, OrderListView,
                          OrderUpdateView, add_quantity, add_to_cart,
                          export_orders_to_excel, remove_from_cart,
                          subtract_quantity, view_cart)

app_name = 'orders'

urlpatterns = [
    path('view/', view_cart, name='view-cart'),
    path('add/<int:product_id>/', add_to_cart, name='add-to-cart'),
    path('add_quantity/<int:cart_item_id>/', add_quantity, name='add-quantity'),
    path('subtract_quantity/<int:cart_item_id>/', subtract_quantity, name='subtract-quantity'),
    path('remove/<int:cart_item_id>/', remove_from_cart, name='remove-from-cart'),
    path('create_order/', OrderCreateView.as_view(), name='create-order'),
    path('order_list/', OrderListView.as_view(), name='order-list'),
    path('order_detail/<int:pk>', OrderDetailView.as_view(), name='order-detail'),
    path('order_update/<int:pk>', OrderUpdateView.as_view(), name='order-update'),
    path('export-orders-to-excel/', export_orders_to_excel, name='export-orders-to-excel'),
]

products/urls.py
from django.urls import path

from products.views import ProductListView

app_name = 'products'

urlpatterns = [
    path("", ProductListView.as_view(), name='product-list'),
    path("page/<int:page>/", ProductListView.as_view(), name='paginator'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category')
]

store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from products.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('auth/', include('users.urls')),
    path('orders/', include('orders.urls')),
    path("", IndexView.as_view(), name="home")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


def upload_to(instance, filename):
    # instance.category - это поле ForeignKey, связывающее продукт с категорией
    category_name = instance.category.name if instance.category else 'uncategorized'
    return f"{category_name}/{filename}"


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField(upload_to=upload_to)
    category = models.ForeignKey(ProductCategory, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

products/views.py
from django.views.generic import ListView, TemplateView

from products.models import Product, ProductCategory


class IndexView(TemplateView):
    template_name = 'products/home.html'


class ProductListView(ListView):
    model = Product
    template_name = 'products/product-list.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        queryset = Product.objects.all()
        category_id = self.kwargs.get('category_id')
        return queryset.filter(category_id=category_id) if category_id else queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context

products/templates/products/home.html
{% extends 'base.html' %}
{% load static %}

products/templates/products/product-list.html
<!-- products/product-list.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container mt-3">
    <div class="row">
      <div class="col-md-3 category-list">
        <!-- Список категорий с использованием стилей Bootstrap -->
        <div class="list-group">
            <a href="{% url 'products:product-list'%}" class="list-group-item list-group-item-action">
              Все категории
            </a>
          {% for category in categories %}
            <a href="{% url 'products:category' category.id %}" class="list-group-item list-group-item-action">
              {{ category.name }}
            </a>
          {% endfor %}
        </div>
      </div>

      <div class="col-md-9">
        <!-- Карточки товаров -->
        <div class="row">
          {% for product in products %}
            <div class="col-md-4 mb-3">
              <div class="card" style="width: 18rem;">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="card-img-top">
                <div class="card-body">
                  <h5 class="card-title">{{ product.name }}</h5>
                  <p class="card-text">{{ product.description }}</p>
                  <h5 class="card-title">{{ product.price }} ₽</h5>
                  <a href="{% url 'orders:add-to-cart' product.id %}" class="btn btn-primary">Добавить в корзину</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>

        <!-- Пагинация с использованием стилей Bootstrap -->
        <!-- Пагинация с использованием стилей Bootstrap -->
            <!-- Пагинация с использованием стилей Bootstrap -->
        {% if is_paginated %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
<!--                        <li class="page-item">-->
<!--                            <a class="page-link" href="?page=1" aria-label="Previous">-->
<!--                                <span aria-hidden="true">&laquo;&laquo;</span>-->
<!--                            </a>-->
<!--                        </li>-->
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}
                        <li class="page-item{% if page_obj.number == i %} active{% endif %}">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
<!--                        <li class="page-item">-->
<!--                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">-->
<!--                                <span aria-hidden="true">&raquo;&raquo;</span>-->
<!--                            </a>-->
<!--                        </li>-->
                    {% endif %}
                </ul>
            </nav>
        {% endif %}


      </div>
    </div>
  </div>
{% endblock %}